name: dart_ffi_mac_ui
description: Example of using ffi with main thread in macOS

environment:
  sdk: ^3.5.1

dependencies:
  native_assets_cli: ^0.10.0
  native_toolchain_c: ^0.7.0

dev_dependencies:
  ffigen: ^15.0.0
  lints: ^5.1.1
  test: ^1.25.0

ffigen:
  name: FfiMacUiThread
  output: 'lib/dart_ffi_mac_ui.dart'
  preamble: |
    // Bindings for `src/dart_ffi_mac_ui.h`.
    // Regenerate bindings with `dart pub run ffigen`.
  headers:
    entry-points:
      - 'src/dart_ffi_mac_ui.h'
  silence-enum-warning: true
  ffi-native: