// Bindings for `src/dart_ffi_mac_ui.h`.
// Regenerate bindings with `dart pub run ffigen`.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ffi_sum_on_current_thread(
  int a,
  int b,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ffi_sum_on_ui_thread(
  int a,
  int b,
);
